### ISSUE TITLE
file uploads fail -  error code 500

### ISSUE THREAD

**Issue by TacitTactics** [kyantech/Palmr#308]
I need help understanding why the files upload is broken and how to fix it. see screenshot of error 500. I have the most basic docker setup running for the latest version. 
tacit@drop:~/palmr$ docker compose down && docker compose pull && docker compose up -d
[+] Running 2/2
 ✔ Container palmr        Removed                                                                                                                                                        1.7s 
 ✔ Network palmr_default  Removed                                                                                                                                                        0.1s 
[+] Pulling 1/1
 ✔ palmr Pulled                                                                                                                                                                          0.2s 
[+] Running 2/2
 ✔ Network palmr_default  Created                                                                                                                                                        0.2s 
 ✔ Container palmr        Started                                                                                                                                                        0.4s 
tacit@drop:~/palmr$ cat docker-compose.yml 
services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    restart: unless-stopped
    ports:
      - "5487:5487" # Web interface
      # - "3333:3333" # API (optional)
      #environment:
      # Optional: Uncomment and configure as needed (if you don`t use, you can remove)
      # - ENABLE_S3=true # Set to true to enable S3-compatible storage
      # - DISABLE_FILESYSTEM_ENCRYPTION=true # Set to false to enable file encryption
      # - ENCRYPTION_KEY=your-secure-key-min-32-chars # Required only if encryption is enabled
      # - PALMR_UID=1000 # UID for the container processes (default is 1000)
      # - PALMR_GID=1000 # GID for the container processes (default is 1000)
      # - SECURE_SITE=false # Set to true if you are using a reverse proxy
      # - DEFAULT_LANGUAGE=en-US # Default language for the application (optional, defaults to en-US)
      # - PRESIGNED_URL_EXPIRATION=3600 # Duration in seconds for presigned URL expiration (optional, defaults to 3600 seconds / 1 hour)
      # - DOWNLOAD_MAX_CONCURRENT=5 # Maximum simultaneous downloads (auto-scales if not set)
      # - DOWNLOAD_MEMORY_THRESHOLD_MB=2048 # Memory threshold in MB before throttling (auto-scales if not set)
      # - DOWNLOAD_QUEUE_SIZE=25 # Maximum queue size for pending downloads (auto-scales if not set)
      # - DOWNLOAD_MIN_FILE_SIZE_GB=3.0 # Minimum file size in GB to activate memory management (default: 3.0)
      # - DOWNLOAD_AUTO_SCALE=true # Enable auto-scaling based on system memory (default: true)
      # - NODE_OPTIONS=--expose-gc # Enable garbage collection for large downloads (recommended for production)
      # - NEXT_PUBLIC_UPLOAD_CHUNK_SIZE_MB=100 # Chunk size in MB for large file uploads (OPTIONAL - auto-calculates if not set)
    volumes:
      - palmr_data:/app/server
 
volumes:
  palmr_data:
tacit@drop:~/palmr$ 

<img width="1915" height="1040" alt="Image" src="https://github.com/user-attachments/assets/95fdc1ba-d449-4ce9-8b58-d794ecb8a69b" />

**Comment by danielalves96** [comment]
Hey! Probably fixed in the version v3.3.0-beta, we recommend following the migration guide to the new version: https://github.com/kyantech/Palmr/discussions/348

Could you conduct another test?

**Comment by gthb96** [comment]
Getting this error for the first time ever after clean installing v3.3.0-beta, not sure what's wrong.
`palmr  | [Multipart] Error creating multipart upload: Error: connect ECONNREFUSED 77.xxx.xxx.xxx:9379
palmr  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1637:16) {
palmr  |   errno: -111,
palmr  |   code: 'ECONNREFUSED',
palmr  |   syscall: 'connect',
palmr  |   address: '77.xxx.xxx.xxx',
palmr  |   port: 9379,
palmr  |   '$metadata': { attempts: 3, totalRetryDelay: 237 }`

Smaller files fail with "Unknown Error" nothing in docker logs

<img width="622" height="442" alt="Image" src="https://github.com/user-attachments/assets/0d157a20-7e97-49e0-b1ae-ac9d99918a75" />

**Comment by danielalves96** [comment]
@gthb96  It looks like Palmr isn’t able to connect to the internal storage endpoint (S3 service) on port 9379, which is the port used by Palmr’s built-in storage service.

The error:

```
Error: connect ECONNREFUSED 77.xxx.xxx.xxx:9379
```

means:

- The palmr container attempted to connect to 77.xxx.xxx.xxx:9379
- The connection was refused (nothing is listening on that port)
- Because of that, the multipart upload cannot start → large uploads fail
- Small uploads also fail with “Unknown Error” since they rely on the same storage endpoint

Likely cause:

You may have HTTPS enabled without a valid SSL setup.

If you set:
```
SECURE_SITE=true
```

but the SSL configuration isn’t correct, the internal storage service will also fail.

How to fix

If you are using HTTP, make sure your STORAGE_URL starts with:
```
http://
```

If you are using HTTPS, ensure the URL is accessible with a valid certificate. The storage service must be reachable over HTTPS as well.

If you want, I can help validate your URL or docker-compose configuration.

**Comment by gthb96** [comment]
Ahh, that makes sense.
77.xxx is my external IP where the STORAGE_URL domain is pointing to.
I reverse proxy to internal Palmr IP:5487 from a different machine via Caddy.

Not sure how to make this work again now, sorry.

Expose internal S3 Port directly on router or through external Caddy instance?
I don't fully understand what's correct way of exposing S3 (to the web, right?)

**Comment by TacitTactics** [comment]
here are the logs from v3.3.0 still no go for file uploads. I am running most basic setup and hitting internal ip over http. almr  | Starting Palmr Application...
palmr  | Storage Mode: false
palmr  | Secure Site: false
palmr  | Encryption: true
palmr  | Database: SQLite
palmr  | 🔐 Fixing permissions for internal storage...
palmr  |    Target user: palmr (UID:1001, GID:1001)
palmr  |    🔧 Setting ownership and permissions...
palmr  |    ✅ Storage directory is writable
palmr  | ✅ Storage ready, starting services...
palmr  | /usr/lib/python3.12/site-packages/supervisor/options.py:13: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
palmr  |   import pkg_resources
palmr  | 2025-12-03 23:37:37,849 INFO Set uid to user 0 succeeded
palmr  | 2025-12-03 23:37:37,849 INFO Set uid to user 0 succeeded
palmr  | 2025-12-03 23:37:37,855 INFO supervisord started with pid 1
palmr  | 2025-12-03 23:37:37,855 INFO supervisord started with pid 1
palmr  | 2025-12-03 23:37:38,858 INFO spawned: 'minio' with pid 16
palmr  | 2025-12-03 23:37:38,858 INFO spawned: 'minio' with pid 16
palmr  | 2025-12-03 23:37:38,865 INFO spawned: 'minio-setup' with pid 17
palmr  | 2025-12-03 23:37:38,865 INFO spawned: 'minio-setup' with pid 17
palmr  | 2025-12-03 23:37:38,871 INFO spawned: 'server' with pid 18
palmr  | 2025-12-03 23:37:38,871 INFO spawned: 'server' with pid 18
palmr  | 2025-12-03 23:37:38,881 INFO spawned: 'web' with pid 19
palmr  | 2025-12-03 23:37:38,881 INFO spawned: 'web' with pid 19
palmr  | [STORAGE-SYSTEM] Initializing storage...
palmr  | 2025-12-03 23:37:38,888 INFO success: minio-setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
palmr  | 2025-12-03 23:37:38,888 INFO success: minio-setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
palmr  | [STORAGE-SYSTEM]   Target user: palmr (UID:1001, GID:1001)
palmr  | [STORAGE-SYSTEM]   Fixing permissions (running as root)...
palmr  | [STORAGE-SYSTEM-SETUP] Starting storage system configuration...
palmr  | [STORAGE-SYSTEM-SETUP] Waiting for storage system to start...
palmr  | 🚀 Starting Palmr Server...
palmr  | ⏳ Waiting for internal storage to initialize...
palmr  |    Waiting for storage... (1/60)
palmr  | [STORAGE-SYSTEM]   ✓ Permissions fixed (owner: 1001:1001)
palmr  | Please wait while Palmr. is starting...
palmr  | [STORAGE-SYSTEM]   ✓ Write test passed
palmr  | 1/2 - Palmr. starting, be patient...
palmr  | [STORAGE-SYSTEM-SETUP]   Waiting... (1/30)
palmr  | [STORAGE-SYSTEM] Generated new root password
palmr  | [STORAGE-SYSTEM] Starting storage server on 0.0.0.0:9379 as user palmr...
palmr  | INFO: Formatting 1st pool, 1 set(s), 1 drives per set.
palmr  | INFO: WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
palmr  | MinIO Object Storage Server
palmr  | Copyright: 2015-2025 MinIO, Inc.
palmr  | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
palmr  | Version: RELEASE.2024-10-13T13-34-11Z (go1.22.8 linux/amd64)
palmr  | 
palmr  | API: http://0.0.0.0:9379 
palmr  | WebUI: http://0.0.0.0:9378 
palmr  | 
palmr  | Docs: https://docs.min.io
palmr  | INFO: 
palmr  |  You are running an older version of MinIO released 10 months before the latest release 
palmr  |  Update: Run `mc admin update ALIAS` 
palmr  | 
palmr  | 
palmr  |    Waiting for storage... (2/60)
palmr  | 2025-12-03 23:37:39,908 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
palmr  | 2025-12-03 23:37:39,908 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
palmr  |    Waiting for storage... (3/60)
palmr  | 1/2 - Palmr. starting, be patient...
palmr  | [STORAGE-SYSTEM-SETUP]   ✓ Storage system is responding
palmr  | [STORAGE-SYSTEM-SETUP] Configuring storage client...
palmr  | [STORAGE-SYSTEM-SETUP] ✗ Failed to configure storage client
palmr  |    Waiting for storage... (4/60)
palmr  | 2025-12-03 23:37:41,911 INFO success: minio entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
palmr  | 2025-12-03 23:37:41,911 INFO success: minio entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
palmr  | 2025-12-03 23:37:41,912 WARN exited: minio-setup (exit status 1; not expected)
palmr  | 2025-12-03 23:37:41,912 WARN exited: minio-setup (exit status 1; not expected)
palmr  |    Waiting for storage... (5/60)
palmr  | 2025-12-03 23:37:42,914 INFO spawned: 'minio-setup' with pid 69
palmr  | 2025-12-03 23:37:42,914 INFO spawned: 'minio-setup' with pid 69
palmr  | [STORAGE-SYSTEM-SETUP] Starting storage system configuration...
palmr  | 2025-12-03 23:37:42,924 INFO success: minio-setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
palmr  | 2025-12-03 23:37:42,924 INFO success: minio-setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
palmr  | [STORAGE-SYSTEM-SETUP] Waiting for storage system to start...
palmr  | [STORAGE-SYSTEM-SETUP]   ✓ Storage system is responding
palmr  | [STORAGE-SYSTEM-SETUP] Configuring storage client...
palmr  | 1/2 - Palmr. starting, be patient...
palmr  | Added `palmr-local` successfully.
palmr  | [STORAGE-SYSTEM-SETUP] Ensuring storage bucket exists: palmr-files...
palmr  | [STORAGE-SYSTEM-SETUP]   Creating bucket 'palmr-files'...
palmr  | Bucket created successfully `palmr-local/palmr-files`.
palmr  | [STORAGE-SYSTEM-SETUP]   ✓ Bucket created
palmr  | [STORAGE-SYSTEM-SETUP] Setting bucket policy...
palmr  | Access permission for `palmr-local/palmr-files` is set to `private`
palmr  | [STORAGE-SYSTEM-SETUP] Saving credentials to /app/server/.minio-credentials...
palmr  | [STORAGE-SYSTEM-SETUP] ✓ Credentials file created and readable
palmr  | [STORAGE-SYSTEM-SETUP] ✓✓✓ Storage system configured successfully!
palmr  | [STORAGE-SYSTEM-SETUP]   Bucket: palmr-files
palmr  | [STORAGE-SYSTEM-SETUP]   Credentials: saved to .minio-credentials
palmr  | [STORAGE-SYSTEM-SETUP]   Palmr will use storage system
palmr  | 2025-12-03 23:37:43,096 INFO exited: minio-setup (exit status 0; expected)
palmr  | 2025-12-03 23:37:43,096 INFO exited: minio-setup (exit status 0; expected)
palmr  | ✅ Internal storage ready!
palmr  | [PALMR] Loading storage system credentials...
palmr  | [PALMR] ✓ Storage system credentials loaded
palmr  | 📂 Data directory: /app/server
palmr  | 💾 Database: file:/app/server/prisma/palmr.db
palmr  | 📁 Creating data directories...
palmr  | 🔐 Ensuring proper ownership for all operations...
palmr  | 📄 Copying configuration files...
palmr  | 🚀 First run detected - setting up database...
palmr  | 🗄️ Creating database schema...
palmr  | 1/2 - Palmr. starting, be patient...
palmr  | Prisma schema loaded from prisma/schema.prisma
palmr  | Datasource "db": SQLite database "palmr.db" at "file:/app/server/prisma/palmr.db"
palmr  | 
palmr  | SQLite database palmr.db created at file:/app/server/prisma/palmr.db
palmr  | 
palmr  | 🚀  Your database is now in sync with your Prisma schema. Done in 325ms
palmr  | 
palmr  | npm notice
palmr  | npm notice New patch version of npm available! 11.6.2 -> 11.6.4
palmr  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.6.4
palmr  | npm notice To update run: npm install -g npm@11.6.4
palmr  | npm notice
palmr  | 🌱 Seeding database...
palmr  | 🌱 Starting app configurations seed...
palmr  | 🛡️  Protected mode: Only creates missing configurations
palmr  | 1/2 - Palmr. starting, be patient...
palmr  | ✅ Created configuration: appName
palmr  | ✅ Created configuration: showHomePage
palmr  | ✅ Created configuration: hideVersion
palmr  | ✅ Created configuration: appDescription
palmr  | ✅ Created configuration: appLogo
palmr  | ✅ Created configuration: firstUserAccess
palmr  | ✅ Created configuration: maxFileSize
palmr  | ✅ Created configuration: maxTotalStoragePerUser
palmr  | ✅ Created configuration: jwtSecret
palmr  | ✅ Created configuration: maxLoginAttempts
palmr  | ✅ Created configuration: loginBlockDuration
palmr  | ✅ Created configuration: passwordMinLength
palmr  | ✅ Created configuration: smtpEnabled
palmr  | ✅ Created configuration: smtpHost
palmr  | ✅ Created configuration: smtpPort
palmr  | ✅ Created configuration: smtpUser
palmr  | ✅ Created configuration: smtpPass
palmr  | ✅ Created configuration: smtpFromName
palmr  | ✅ Created configuration: smtpFromEmail
palmr  | ✅ Created configuration: smtpSecure
palmr  | ✅ Created configuration: smtpNoAuth
palmr  | ✅ Created configuration: smtpTrustSelfSigned
palmr  | ✅ Created configuration: passwordResetTokenExpiration
palmr  | ✅ Created configuration: authProvidersEnabled
palmr  | ✅ Created configuration: passwordAuthEnabled
palmr  | ✅ Created configuration: serverUrl
palmr  | 
palmr  | 📊 Seed Summary:
palmr  |    ✅ Created: 26 configurations
palmr  |    ⏭️  Skipped: 0 configurations
palmr  | 🎉 App configurations seeded successfully!
palmr  | 
palmr  | 🔐 Starting auth providers seed...
palmr  | 🛡️  Protected mode: Only creates missing providers
palmr  | ✅ Created auth provider: Google (google)
palmr  | ✅ Created auth provider: Discord (discord)
palmr  | ✅ Created auth provider: GitHub (github)
palmr  | ✅ Created auth provider: Auth0 (auth0)
palmr  | ✅ Created auth provider: Kinde Auth (kinde)
palmr  | ✅ Created auth provider: Zitadel (zitadel)
palmr  | ✅ Created auth provider: Authentik (authentik)
palmr  | ✅ Created auth provider: Frontegg (frontegg)
palmr  | ✅ Created auth provider: Pocket ID (pocketid)
palmr  | 
palmr  | 📊 Auth Providers Summary:
palmr  |    ✅ Created: 9 providers
palmr  |    ⏭️  Skipped: 0 providers
palmr  | 🎉 Auth providers seeded successfully!
palmr  | ✅ Database setup completed!
palmr  | 🚀 Starting Palmr server...
palmr  | 🔽 Dropping privileges to UID:GID 1000:1000
palmr  | [STORAGE] Using internal storage system
palmr  | 1/2 - Palmr. starting, be patient...
palmr  | 2025-12-03 23:37:49,037 INFO success: web entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
palmr  | 2025-12-03 23:37:49,037 INFO success: web entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
palmr  | [MIGRATION] No filesystem files found, nothing to migrate
palmr  | [MIGRATION] Migration marked as complete
palmr  | 📦 Using internal storage (auto-configured)
palmr  | 🌴 Palmr server running on port 3333
palmr  | 2/2 - Palmr. starting, be patient...
palmr  |    ▲ Next.js 15.3.4
palmr  |    - Local:        http://localhost:5487
palmr  |    - Network:      http://0.0.0.0:5487
palmr  | 
palmr  |  ✓ Starting...
palmr  |  ✓ Ready in 203ms
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:38:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/palmr-files/.usage-cache.bin (cmd.PrefixAccessDenied)
palmr  |        3: internal/logger/logger.go:268:logger.LogIf()
palmr  |        2: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        1: cmd/erasure.go:566:cmd.erasureObjects.nsScanner.func2()
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:38:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.usage-cache.bin (cmd.PrefixAccessDenied)
palmr  |        4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
palmr  |        3: internal/logger/logonce.go:149:logger.LogOnceIf()
palmr  |        2: cmd/logging.go:140:cmd.scannerLogOnceIf()
palmr  |        1: cmd/erasure.go:465:cmd.erasureObjects.nsScanner.func1()
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:38:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.bloomcycle.bin, Object buckets/.bloomcycle.bin (*fmt.wrapError)
palmr  |        4: internal/logger/logger.go:268:logger.LogIf()
palmr  |        3: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        2: cmd/data-scanner.go:231:cmd.runDataScanner()
palmr  |        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:38:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.usage.json (cmd.PrefixAccessDenied)
palmr  |        4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
palmr  |        3: internal/logger/logonce.go:149:logger.LogOnceIf()
palmr  |        2: cmd/logging.go:140:cmd.scannerLogOnceIf()
palmr  |        1: cmd/data-usage.go:59:cmd.storeDataUsageInBackend()
palmr  | Error in getPresignedUrl: Error: [STORAGE] STORAGE_URL environment variable is required when using internal storage (ENABLE_S3=false). Set STORAGE_URL to your public storage URL with protocol (e.g., https://syrg.palmr.com or http://192.168.1.100:9379)
palmr  |     at createPublicS3Client (/app/palmr-app/dist/config/storage.config.js:144:19)
palmr  |     at S3StorageProvider.getPresignedPutUrl (/app/palmr-app/dist/providers/s3-storage.provider.js:68:66)
palmr  |     at FileService.getPresignedPutUrl (/app/palmr-app/dist/modules/file/service.js:12:43)
palmr  |     at FileController.getPresignedUrl (/app/palmr-app/dist/modules/file/controller.js:32:48)
palmr  |     at preHandlerCallbackInner (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:161:24)
palmr  |     at preHandlerCallback (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:129:5)
palmr  |     at validationCompleted (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:119:5)
palmr  |     at preValidationCallback (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/handleRequest.js:96:5)
palmr  |     at next (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:236:9)
palmr  |     at handleResolve (/app/palmr-app/node_modules/.pnpm/fastify@5.4.0/node_modules/fastify/lib/hooks.js:253:7)
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:39:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/palmr-files/.usage-cache.bin (cmd.PrefixAccessDenied)
palmr  |        3: internal/logger/logger.go:268:logger.LogIf()
palmr  |        2: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        1: cmd/erasure.go:566:cmd.erasureObjects.nsScanner.func2()
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:39:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.bloomcycle.bin, Object buckets/.bloomcycle.bin (*fmt.wrapError)
palmr  |        4: internal/logger/logger.go:268:logger.LogIf()
palmr  |        3: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        2: cmd/data-scanner.go:231:cmd.runDataScanner()
palmr  |        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:40:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/palmr-files/.usage-cache.bin (cmd.PrefixAccessDenied)
palmr  |        3: internal/logger/logger.go:268:logger.LogIf()
palmr  |        2: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        1: cmd/erasure.go:566:cmd.erasureObjects.nsScanner.func2()
palmr  | 
palmr  | API: SYSTEM.scanner
palmr  | Time: 23:40:39 UTC 12/03/2025
palmr  | DeploymentID: 01e7f53e-8955-456a-a242-02fc9f43c93d
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.bloomcycle.bin, Object buckets/.bloomcycle.bin (*fmt.wrapError)
palmr  |        4: internal/logger/logger.go:268:logger.LogIf()
palmr  |        3: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        2: cmd/data-scanner.go:231:cmd.runDataScanner()
palmr  |        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()

<img width="1907" height="1040" alt="Image" src="https://github.com/user-attachments/assets/9aa822f0-9423-46cf-b377-ec3fde24d96b" />

**Comment by TacitTactics** [comment]
I do not understand why the error tells me to configure a port that the application does not use.  I do not want to use S3, so I set the variable to 'false", I still had to set the Storage_URL variable to the IP address at the port that does not exist. Now I just get an unknown error which is most likely due to the application trying to hit a port not even open. 
tacit@drop:~/palmr$ ss -ntlpu
Netid           State            Recv-Q           Send-Q                                                 Local Address:Port                      Peer Address:Port          Process           
udp             UNCONN           0                0                                                            0.0.0.0:41641                          0.0.0.0:*                               
udp             UNCONN           0                0                                                         127.0.0.54:53                             0.0.0.0:*                               
udp             UNCONN           0                0                                                      127.0.0.53%lo:53                             0.0.0.0:*                               
udp             UNCONN           0                0                                                192.168.3.116%ens18:68                             0.0.0.0:*                               
udp             UNCONN           0                0                                                               [::]:41641                             [::]:*                               
tcp             LISTEN           0                4096                                                      127.0.0.54:53                             0.0.0.0:*                               
tcp             LISTEN           0                4096                                                         0.0.0.0:3333                           0.0.0.0:*                               
tcp             LISTEN           0                4096                                                         0.0.0.0:5487                           0.0.0.0:*                               
tcp             LISTEN           0                4096                                                   127.0.0.53%lo:53                             0.0.0.0:*                               
tcp             LISTEN           0                511                                                          0.0.0.0:9091                           0.0.0.0:*                               
tcp             LISTEN           0                4096                                                   100.90.208.13:52182                          0.0.0.0:*                               
tcp             LISTEN           0                4096                                                            [::]:3333                              [::]:*                               
tcp             LISTEN           0                4096                                                            [::]:5487                              [::]:*                               
tcp             LISTEN           0                4096                                                               *:22                                   *:*                               
tcp             LISTEN           0                50                                                                 *:9090                                 *:*                               
tcp             LISTEN           0                511                                                             [::]:9091                              [::]:*                               
tcp             LISTEN           0                4096                       [fd7a:115c:a1e0:f815:4ce6:5afe:ddbd:6f27]:63058                             [::]:*   

why did it ask for an IP address other than  itself? http://192.168.1.100:9379/

**Comment by danielalves96** [comment]
> Ah, entendi. 77.xxx é meu IP externo, para onde o domínio STORAGE_URL está apontando. Eu faço proxy reverso para o IP interno do Palmr (5487) a partir de outra máquina via Caddy.
> 
> Não sei como fazer isso funcionar novamente agora, desculpe.
> 
> Expor a porta S3 interna diretamente no roteador ou através de uma instância externa do Caddy? Não entendi completamente qual é a maneira correta de expor o S3 (para a web, certo?).

I recommend exposing port `9379` through Caddy like `5487` and setting `STORAGE_URL` to your new URL proxied by caddy. This is the simplest and most reliable way to get everything working. In this version, you still need to provide this URL even if everything is being handled internally by Palmr. I’m working on a way to simplify this process, but I haven’t had success yet.

**Comment by danielalves96** [comment]
@TacitTactics 

Even if you choose not to use S3, Palmr still runs an internal S3-compatible API inside the container, which means defining a STORAGE_URL is mandatory. For that reason, you need to expose port 9379 (where the S3-compatible API runs) and set something like `http://your_server_ip:9379` or `http://localhost:9379` (if running locally) in the STORAGE_URL environment variable.

The recommended setup is to expose everything through a reverse proxy such as Nginx, Caddy, Traefik, etc.

Below is the screenshot from your logs showing that the container is indeed running the internal S3 API:

<img width="236" height="92" alt="Image" src="https://github.com/user-attachments/assets/b7fdd4ea-740f-4db5-ae12-a345bf036643" />

**Comment by gthb96** [comment]
I understand, thank you Daniel.
So far I couldn't get it to work by exposing 9379 through Caddy.
Could be an issue with caddy config, not sure.
`palmr.domain.com {
        reverse_proxy 192.168.10.35:5487
}
palmr.domain.com:9379 {
       reverse_proxy 192.168.10.35:9379
}`

**Comment by TacitTactics** [comment]
what about updating the docker-compose.yml to include the suggested Reverse proxy configured properly. This way you the project would continue to get the positive attention in deserves. This is an awesome beta that I think will be bounds ahead of any other alternative like Sharry.

Another thought, what about adding the https://github.com/minio/minio container to your docker-compose.yml? 

the MinIO maybe a best option because this would ensure ports are exposed to host machine without additional challenges and your project can focus less on storage until after full launch.

**Comment by TacitTactics** [comment]
Thank you for the new docker compose.yml file. I am getting this error with 61mb file

Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. login
port disconnected from addon code: 5d2caacf-bcb8-49bf-861f-2da8701e4146 browser-integration.js:2:31242
The resource at “http://100.90.208.13:5487/_next/static/media/0484562807a97172-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/155cae559bbd1a77-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/47cbc4e2adbc5db9-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/4c285fdca692ea22-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/4de1fea1a954a5b6-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/55c20a7790588da9-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/6245472ced48d3be-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/630c17af355fa44e-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/6d664cce900333ee-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7108afb8b1381ad1-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7db6c35d839a711c-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7ff6869a1704182a-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/8888a3826f4a3af4-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/904be59b21bd51cb-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/9cf9c6e84ed13b5e-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/9e82d62334b205f4-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/b957ea75a84b6ea7-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/c9e6921c7fc300d8-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/e4af272ccee01ff0-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/e807dee2426166ad-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/eafabf029ad39a43-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/ee40bb094c99a29a-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. login
NotSupportedError: HTMLElement.hidePopover: Element is in the no popover state 148 bootstrap-autofill-overlay.js:2919
Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}. 9434-3e3f7b7992318b14.js:1:7500
[Upload:Multipart] Failed to create multipart upload: 
Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, status: 500, stack: "", … }
5097-d7b5d68dc54b7e44.js:1:155094
[Uppy] [12:53:35] Request failed with status code 500 5097-d7b5d68dc54b7e44.js:1:155094
[Upload] Upload failed: Git-2.51.0-64-bit.exe 
Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, status: 500, stack: "", … }
5097-d7b5d68dc54b7e44.js:1:155094

<img width="3791" height="2325" alt="Image" src="https://github.com/user-attachments/assets/82bf470a-71c7-4bcf-9f8c-f341bf06cd65" />


when I did a smaller file of 17kb I got this error 
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. login
port disconnected from addon code: 511d93fd-a535-4617-95d5-e58a1012628f browser-integration.js:2:31242
The resource at “http://100.90.208.13:5487/_next/static/media/0484562807a97172-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/155cae559bbd1a77-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/47cbc4e2adbc5db9-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/4c285fdca692ea22-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/4de1fea1a954a5b6-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/55c20a7790588da9-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/6245472ced48d3be-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/630c17af355fa44e-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/6d664cce900333ee-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7108afb8b1381ad1-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7b0b24f36b1a6d0b-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7db6c35d839a711c-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/7ff6869a1704182a-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/8888a3826f4a3af4-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/904be59b21bd51cb-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/9cf9c6e84ed13b5e-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/9e82d62334b205f4-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/b957ea75a84b6ea7-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/c9e6921c7fc300d8-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/e4af272ccee01ff0-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/e807dee2426166ad-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/eafabf029ad39a43-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “http://100.90.208.13:5487/_next/static/media/ee40bb094c99a29a-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
NotSupportedError: HTMLElement.hidePopover: Element is in the no popover state 21 bootstrap-autofill-overlay.js:2919
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen. login
NotSupportedError: HTMLElement.hidePopover: Element is in the no popover state 39 bootstrap-autofill-overlay.js:2919
Warning: Missing `Description` or `aria-describedby={undefined}` for {DialogContent}. 9434-3e3f7b7992318b14.js:1:7500
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://100.90.208.13:9379/palmr-files/cmirqozv50000l70jkcjn2l6o/1764871133525-nsec0r-yuE8NHmhw6bf.ravricsolutions?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=palmr-minio-admin%2F20251204%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20251204T175853Z&X-Amz-Expires=3600&X-Amz-Signature=36608f868d9fd9b3fe922055f2e0b3226267b4e7eb96850261208c52be7e051a&X-Amz-SignedHeaders=host&x-amz-checksum-crc32=AAAAAA%3D%3D&x-amz-sdk-checksum-algorithm=CRC32&x-id=PutObject. (Reason: CORS request did not succeed). Status code: (null). 2
[Uppy] [12:58:54] Unknown error 5097-d7b5d68dc54b7e44.js:1:155094
[Upload] Upload failed: ravricsolutions Error: Unknown error
    uploadPartBytes NextJS
5097-d7b5d68dc54b7e44.js:1:155094


Looks like minio issue based on this 
palmr  | API: SYSTEM.scanner
palmr  | Time: 18:03:49 UTC 12/04/2025
palmr  | DeploymentID: 38feb03f-071c-4057-b619-6c66dbcf9606
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.bloomcycle.bin, Object buckets/.bloomcycle.bin (*fmt.wrapError)
palmr  |        4: internal/logger/logger.go:268:logger.LogIf()
palmr  |        3: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        2: cmd/data-scanner.go:231:cmd.runDataScanner()
palmr  |        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()
palmr  |
palmr  | API: SYSTEM.scanner
palmr  | Time: 18:04:49 UTC 12/04/2025
palmr  | DeploymentID: 38feb03f-071c-4057-b619-6c66dbcf9606
palmr  | Error: Prefix access is denied: .minio.sys/buckets/palmr-files/.usage-cache.bin (cmd.PrefixAccessDenied)
palmr  |        3: internal/logger/logger.go:268:logger.LogIf()
palmr  |        2: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        1: cmd/erasure.go:566:cmd.erasureObjects.nsScanner.func2()
palmr  |
palmr  | API: SYSTEM.scanner
palmr  | Time: 18:04:49 UTC 12/04/2025
palmr  | DeploymentID: 38feb03f-071c-4057-b619-6c66dbcf9606
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.bloomcycle.bin, Object buckets/.bloomcycle.bin (*fmt.wrapError)
palmr  |        4: internal/logger/logger.go:268:logger.LogIf()
palmr  |        3: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        2: cmd/data-scanner.go:231:cmd.runDataScanner()
palmr  |        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()
palmr  |
palmr  | API: SYSTEM.scanner
palmr  | Time: 18:05:49 UTC 12/04/2025
palmr  | DeploymentID: 38feb03f-071c-4057-b619-6c66dbcf9606
palmr  | Error: Prefix access is denied: .minio.sys/buckets/palmr-files/.usage-cache.bin (cmd.PrefixAccessDenied)
palmr  |        3: internal/logger/logger.go:268:logger.LogIf()
palmr  |        2: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        1: cmd/erasure.go:566:cmd.erasureObjects.nsScanner.func2()
palmr  |
palmr  | API: SYSTEM.scanner
palmr  | Time: 18:05:49 UTC 12/04/2025
palmr  | DeploymentID: 38feb03f-071c-4057-b619-6c66dbcf9606
palmr  | Error: Prefix access is denied: .minio.sys/buckets/.bloomcycle.bin, Object buckets/.bloomcycle.bin (*fmt.wrapError)
palmr  |        4: internal/logger/logger.go:268:logger.LogIf()
palmr  |        3: cmd/logging.go:136:cmd.scannerLogIf()
palmr  |        2: cmd/data-scanner.go:231:cmd.runDataScanner()
palmr  |        1: cmd/data-scanner.go:82:cmd.initDataScanner.func1()

**Comment by TacitTactics** [comment]
Solution: 

add uid and gid in docker-compose.yml file

services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    restart: unless-stopped
    ports:
      - "100.90.208.13:5487:5487"  # Web UI
      - "100.90.208.13:3333:3333"  # API (optional)
      - "100.90.208.13:9379:9379"  # Internal MinIO API (your request)
    env_file:
      - .env
    volumes:
      - palmr_data:/app/server
    environment:
      # Storage: Internal MinIO (default, zero-config)
      ENABLE_S3: "false"  # Disables external S3, uses internal
      **# UID/GID: Match host to fix permission denied on .minio-credentials
      PALMR_UID: "1000"
      PALMR_GID: "1000"**
      # Other (from your provided config)
      SECURE_SITE: "false"  # Set true for HTTPS
    # No depends_on or networks needed for single-container internal setup

volumes:
  palmr_data:

also had to set ownership of palmr_data
everything worked wonderfully

<img width="3743" height="2312" alt="Image" src="https://github.com/user-attachments/assets/545fa118-79ca-4ccc-8bf0-441a45eb3661" />
